FROM python:3.10-slim

WORKDIR /app

COPY streamlit_app /app/streamlit_app
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/app.py", "--server.address=0.0.0.0"]