FROM python:3.10-slim 

# Create working directory
WORKDIR /app

ENV PYTHONPATH="/app"

# Copy project
COPY src/ /app/src
COPY trained_models /app/trained_models


COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Start FastAPI server
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
